on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: yamllint .
