---
on:
  - push
  - pull_request
jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install -r requirements.txt
      - run: yamllint .
    runs-on: ubuntu-latest
